title: Terminally Curious
logo: "/images/icon_trans.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Code, Queries & Curiousity!
  SELECT * FROM life
  
remote_theme: pages-themes/modernist
plugins:
- jekyll-remote-theme
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
